/* autogenerated by Processing revision 1291 on 2023-02-21 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class picking_colours extends PApplet {

PImage img;

public void setup(){
  /* size commented out by preprocessor */;
  img = loadImage("mlk.jpg");
}

public void draw(){
  background(0xFFF1F1F1);
  image(img,0,0);
  noStroke();
  int c = img.get(mouseX,mouseY);
  fill(c);
  ellipse(mouseX,mouseY,250,250);
}


  public void settings() { size(1200, 900); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "picking_colours" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
